#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"


cat <<EOF >&2
   
NAME
   ${SERVICENAME} - store low security secrets in AWS S3.
   
SYNOPSIS
   S3KEY=? S3SECRET=? BUCKET=? ${SERVICENAME} configure    - Set up the S3 bucket.
   ${SERVICENAME} store < MYFILE                           - Store a secret.
   PASS=? ${SERVICENAME} store MYNAME < MYFILE             - Store named secret.
   
DESCRIPTION
   See https://github.com/j842/docker-simplesecrets
EOF
