#!/bin/bash

# restore
#
# This file is run on the host, and restores any configuration or data
# that is outside /dr/config from the backup in RESTOREPATH.
#

SERVICENAME="$1"
IMAGENAME="$2"
RESTOREPATH="$3"

# Nothing to do. 

cat "$RESTOREPATH/note.txt" >&2
