#!/bin/bash

SERVICENAME="$1"
CONTAINERNAME="$2"
shift 2

# This script is run on the host.
# It launches the docker container and runs our hello world command.

VOLUME_VCMD="simplesecrets-${SERVICENAME}-config:/config"
               
docker run --name=simplesecrets -i -v "${VOLUME_VCMD}" -e "PASS=\${PASS}" \
       ${CONTAINER_NAME} /usr/local/bin/simplesecrets $@
 
 docker rm simplesecrets
 