#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# backup
#
# This file is run on the host, and backs up any configuration
# or data stored outside /dr/config
# Backups need to be stored in BACKUPPATH. We can use whatever
# format we want for the files, we restore them in the restore
# script.
#

BACKUPPATH="$1"

# Nothing to do, our configuration is handled by Docker Runner
# since it's in the standard /config folder.

