#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"

# This script is run on the host.
# It launches the docker container and runs our hello world command.

docker run -i -t --name="${SERVICENAME}-enter" -h "${HOSTNAME}" ${DOCKEROPTS[@]} \
               ${IMAGENAME} /bin/bash

docker rm "${SERVICENAME}-enter" >/dev/null
