#!/bin/bash
source "$( dirname "$(readlink -f "$0")" )/_variables"



function showusage {
cat <<EOF

NAME
   ${SERVICENAME} store - upload simple secrets to S3
   
SYNOPSIS
   ${SERVICENAME} store < myfile 
   PASS=PASSWORD ${SERVICENAME} store NAME < myfile

DESCRIPTION
   Uploads the encrypted file (or data) to the configured S3 bucket in /simplesecrets.
   PASSWORD is as specified, or randomly generated otherwise.
   NAME is as specified, or the MD5 of the file otherwise.
   
   If NAME matches an existing file it is overwritten. This allows updating with the
   same NAME and PASSWORD, as well as updating the PASSWORD and keeping the name the
   same.

RETURN VALUE
   0   - success
   1   - error
   
EOF
   exit 1  
}

# This script is run on the host.
# It launches the docker container and runs our hello world command.

if [ $# -gt 1 ]; then echo "Expected up to one argument. Got ${#} - $@" ; showusage; fi
               
docker run --name=simplesecrets -i ${DOCKEROPTS[@]} -e "PASS=${PASS}" \
       ${IMAGENAME} store "$@"
 
docker rm simplesecrets >/dev/null
 